const nodemailer = require('nodemailer');
const fs = require('fs');
const path = require('path');
require('dotenv').config();

async function sendReportEmail() {
    if (require.main === module) {
        console.log('\n======================================================================');
        console.log('✉️ Phase 4: Email Distribution');
        console.log('======================================================================');
    }
    
    const reportJsonPath = path.resolve(__dirname, '../monocart-report/index.json');
    if (!fs.existsSync(reportJsonPath)) {
        console.error('Report data not found. Cannot send email.');
        return;
    }

    // Read the actual report summary
    const reportData = JSON.parse(fs.readFileSync(reportJsonPath, 'utf8'));
    const { summary } = reportData;
    
    // Extract real-time metrics
    const totalTests = summary.tests?.value ?? 0;
    const passedTests = summary.passed?.value ?? 0;
    const failedTests = summary.failed?.value ?? 0;
    const executionDuration = reportData.durationH || summary.durationH || 'N/A';
    
    const executionDate = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
    const isSuccess = failedTests === 0;
    const overallStatusText = isSuccess ? '✅ PASSED' : '❌ FAILED';
    const statusColor = isSuccess ? '#28a745' : '#d9534f';
    const resultType = isSuccess ? 'Success' : 'Alert';
    const passRate = `${passedTests}/${totalTests} Passed`;
    const orgName = process.env.ORG_NAME || 'JISA Softech';
    const teamName = process.env.TEAM_NAME || 'QA Automation Team';
    const projectName = process.env.PROJECT_NAME || 'EKMS API Automation';


    const transporter = nodemailer.createTransport({
        host: process.env.SMTP_HOST,
        port: process.env.SMTP_PORT,
        secure: false, 
        auth: {
            user: process.env.SMTP_USER,
            pass: process.env.SMTP_PASS,
        },
    });

    const htmlBody = `
        <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; width: 100%; color: #333; line-height: 1.6; padding: 20px; box-sizing: border-box;">
            <p>Dear Team,</p>
            <p>Please find below the summary of the EKMS API test execution:</p>
            
            <hr style="border: none; border-top: 1px solid #eee; margin: 15px 0;" />
            
            <p style="margin: 5px 0;"><strong>🔹 Organization:</strong> ${orgName}</p>
            <p style="margin: 5px 0;"><strong>🔹 Test Suite:</strong> ${projectName}</p>
            <p style="margin: 5px 0;"><strong>🔹 Execution Date:</strong> ${executionDate}</p>
            <p style="margin: 5px 0;"><strong>🔹 Overall Status:</strong> <span style="color: ${statusColor}; font-weight: bold;">${overallStatusText}</span></p>
            
            <hr style="border: none; border-top: 1px solid #eee; margin: 15px 0;" />
            
            <h3 style="color: #2c3e50;">📊 Execution Summary</h3>
            <ul style="list-style: none; padding-left: 0;">
                <li style="margin-bottom: 8px;"><strong>• Total Test Cases:</strong> ${totalTests}</li>
                <li style="margin-bottom: 8px;"><strong>• Passed:</strong> ${passedTests}</li>
                <li style="margin-bottom: 8px;"><strong>• Failed:</strong> ${failedTests}</li>
                <li style="margin-bottom: 8px;"><strong>• Execution Duration:</strong> ${executionDuration}</li>
            </ul>
            
            <hr style="border: none; border-top: 1px solid #eee; margin: 15px 0;" />
            
            <p>The test suite execution has completed, and <strong>${isSuccess ? 'all test cases have passed as expected.' : failedTests + ' test case(s) failed, which requires immediate attention and investigation.'}</strong></p>
            
            <p><strong>📎 Detailed Report:</strong><br/>
            Please refer to the attached PDF report for complete validation details, including request/response logs and trace information.</p>
            
            <hr style="border: none; border-top: 1px solid #eee; margin: 15px 0;" />
            
            <p>If you need any additional information or support, please feel free to contact the ${teamName}.</p>
            
            <p>Best regards,<br/>
            <strong>${teamName}</strong><br/>
            <strong>${orgName}</strong></p>
            
            <p style="margin-top: 20px; font-size: 11px; color: #777; font-style: italic;">Auto-generated by ${projectName} Framework</p>
        </div>
    `;

    // Support multiple recipients by sending individual emails (most reliable for different domains)
    const recipientList = (process.env.EMAIL_TO || '').split(',').map(email => email.trim()).filter(email => email !== '');

    if (recipientList.length === 0 || !process.env.SMTP_USER || process.env.SMTP_USER.includes('your-email')) {
        console.log('Skipping email send: Recipients or SMTP credentials not configured.');
        return;
    }

    console.log(`Sending individual reports to ${recipientList.length} recipients concurrently...`);

    const emailPromises = recipientList.map(async (recipient) => {
        const mailOptions = {
            from: `"${process.env.FROM_NAME || 'EKMS Automation'}" <${process.env.SMTP_USER}>`,
            to: recipient,
            subject: `[${resultType}] ${projectName} Report – ${isSuccess ? 'PASSED' : 'FAILED'} (${passRate}) | ${executionDate}`,
            html: htmlBody,
            attachments: [
                {
                    filename: 'test-report.pdf',
                    path: path.resolve(__dirname, '../test-report.pdf'),
                }
            ]
        };

        try {
            await transporter.sendMail(mailOptions);
            console.log(`[SUCCESS] Report sent to: ${recipient}`);
        } catch (error) {
            console.error(`[FAILED] Could not send report to ${recipient}:`, error.message);
        }
    });

    await Promise.all(emailPromises);
    
    if (require.main === module) {
        console.log(`\nFinal Stats: ${totalTests} Total | ${passedTests} Passed | ${failedTests} Failed`);
    }
}

if (require.main === module) {
    sendReportEmail();
}

module.exports = sendReportEmail;
